name: Build and Test
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        omp: [OFF, ON]
        mpi: [OFF, ON]
    name: Build and Test
    # This job runs on Linux
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR: build_${{ matrix.omp }}_${{ matrix.mpi }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Debug
        run: ls -a
      - name: Install dependencies
        run: sudo apt install -y libopenblas-dev liblapack-dev libscalapack-openmpi-dev
      - name: Configure
        run: |
          mkdir ${BUILD_DIR}
          cd ${BUILD_DIR}
          cmake .. -DOMP_AVAIL=${{ matrix.omp }} -DKokkos_ENABLE_OPENMP=${{ matrix.omp }} -DMPI_AVAIL=${{ matrix.mpi }}
      - name: Build
        run: |
          cd ${BUILD_DIR}
          make -j4
      - name: Run example
        working-directory: example/Silicon
        run: ../../${BUILD_DIR}/phoebe -in input.in
