name: Build and Test
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    # This job runs on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Debug
        run: ls -a
      - name: Install dependencies
        run: sudo apt install -y libopenblas-dev liblapack-dev libscalapack-openmpi-dev
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: make -j4
        working-directory: build
      - name: Run example
        working-directory: example/Silicon
        run: ../../build/phoebe -in input.in
