name: MacOS Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        omp: [OFF]
        mpi: [ON]
    name: "(OpenMP, MPI) = OFF, ON"
    runs-on: macos-latest
    env:
      BUILD_DIR: build_${{ matrix.omp }}_${{ matrix.mpi }}
    steps:
      - name: Install dependencies
        run: |
          brew install gcc open-mpi openblas lapack hdf5 scalapack
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure
        run: |
          mkdir ${BUILD_DIR}
          cd ${BUILD_DIR}
          cmake .. -DOMP_AVAIL=${{ matrix.omp }} -DKokkos_ENABLE_OPENMP=${{ matrix.omp }} -DMPI_AVAIL=${{ matrix.mpi }} -DHDF5_AVAIL=ON -DHDF5_SERIAL=ON
      - name: Build
        run: |
          cd ${BUILD_DIR}
          make -j4
